### ISSUE TITLE
[IMPROVE] Dynamic loading of Pickle data

### ISSUE THREAD

**Issue by AlexAltea** [JerBouma/FinanceDatabase#33]
Related: https://github.com/OpenBB-finance/OpenBBTerminal/issues/4422

Not sure if to flag this as a bug or improvement (probably rather a security vulnerability). Either way, I think it's fairly dangerous to have terminals download on-demand Pickle files from random places on the Internet.

Pickle files allow for remote code execution and Python offers no sandbox mechanism. This is not so different from loading a DLL. See the warning at: https://docs.python.org/3/library/pickle.html or https://pandas.pydata.org/docs/reference/api/pandas.read_pickle.html

---

**What's the feature or data that should be improved?**

Code should move away from dynamically loading Pickle containers, e.g.: https://github.com/JerBouma/FinanceDatabase/blob/3d55640f566de9cc8dd77acd774840c9a4fc8f40/financedatabase/helpers.py#L47

**Describe how you would like the feature improved**

Same functionality using a safe serialization format.

**Possibly describe the ideal way to improve this**

E.g. [msgpack](https://msgpack.org/), BSON or compressed JSON instead of Pickle.

**Additional information**

N/A

**Comment by JerBouma** [comment]
So I don't entirely see the issue here. As you say I am in full control of the database but I am also affiliated directly with OpenBB. There are no incentives for me whatsoever to include malicious code.

Furthermore, the database is setup in such a way that in no circumstances I would accept a PR that changes the pickles, that's what I have GitHub Actions for. You would need to add the malicious code directly into the CSV file for it to work and have it activate only if you read a pickle and not a CSV.

Lots of steps you need to take to achieve such a feat and therefore I don't really see the risk or major security issue.

**Comment by JerBouma** [comment]
Fixed with new release.

**Comment by AlexAltea** [comment]
Thank you very much for the quick answer and your fix!

> There are no incentives for me whatsoever to include malicious code.

Absolutely, my concern was rather. What if a reviewer overlooks a malicious PR? What if your account gets compromised? What if GitHub or an Actions runner gets compromised? I understand chances of this are very low, but the impact of 100,000's of users dynamically downloading files that can run arbitrary code without a sandbox was nightmare material for me.

Thanks a lot for taking care of this. ❤️
