### ISSUE TITLE
industry field anomalies

### ISSUE THREAD

**Issue by mrx23dot** [JerBouma/FinanceDatabase#6]
https://github.com/JerBouma/FinanceDatabase/raw/master/Database/Equities/Countries/United%20States/United%20States.json

"industry" field contains the following anomaly:
```

"Banks\u2014Diversified",
"Banks\u2014Regional",
"Beverages\u2014Brewers",
"Beverages\u2014Non-Alcoholic",
"Beverages\u2014Wineries & Distilleries",

"Drug Manufacturers\u2014General",
"Drug Manufacturers\u2014Specialty & Generic",
"Insurance\u2014Diversified",
"Insurance\u2014Life",
"Insurance\u2014Property & Casualty",
"Insurance\u2014Reinsurance",
"Insurance\u2014Specialty",
"Real Estate\u2014Development",
"Real Estate\u2014Diversified",

```

these could use some normalization
"Aerospace & Defense",
"Aerospace/Defense - Major Diversified",
"Aerospace/Defense Products & Services",

It's a lot faster to work on offline database, cheers!

**Comment by JerBouma** [comment]
Ah, I fixed this within my `search_products` function. I will look into adjusting the JSON files as well!

**Comment by JerBouma** [comment]
Fixed the issue. The problem was that  `\u2014\` referred to a special form of the dash ( - ) sign. This makes it very difficult to select that type of data. See the fix (for example): [Banks - Diversified]((https://github.com/JerBouma/FinanceDatabase/blob/master/Database/Equities/Industries/Banks%20-%20Diversified.json).

I also updated strings like `Aerospace/Defense Products & Services` to `Aerospace Defense Products & Services` because the forward slash usually gives problems with filenames.

Please let me know if you find more weird unicodes!
