### ISSUE TITLE
[FR] List of ETFs and stocks

### ISSUE THREAD

**Issue by sam1946** [JerBouma/FinanceDatabase#73]
Hi, this is less of an issue and more of a request.

- How do I get a list of all ETFs that are in the UK?
- Can I get a list of which ETF is leveraged and non-leveraged?
- Can I get a list of all stocks in an index, eg- S&P500

Thanks!

**Comment by JerBouma** [comment]
Hereby the answers:

**How do I get a list of all ETFs that are in the UK?**
Unfortunately this is not possible. The main purpose of the Finance Database is to allow you to look into Equities which is why you can use the Select function to search per country in that case.

<img width="1093" alt="Screenshot 2024-01-21 at 18 12 54" src="https://github.com/JerBouma/FinanceDatabase/assets/46355364/c96dc6f3-df19-4e72-a142-20c3baff8e19">

**Can I get a list of which ETF is leveraged and non-leveraged?**

This is not supported and will most likely never be given that the main purpose is to provide general insights into Equities.

**Can I get a list of all stocks in an index, eg- S&P500**

You can use for example https://www.ssga.com/us/en/intermediary/etfs/library-content/products/fund-data/etfs/us/holdings-daily-us-en-spy.xlsx and extract those directly from the Finance Database Equities dataset. This should be doable for any index. I can not provide a special column for this given that it frequently changes and there are too many indices that would overlap for individual companies.

**Comment by sam1946** [comment]
No probs and thank you for all your hard work :)
